# Generated by Django 4.2.1 on 2023-05-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoran',
            name='RestoranName',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restoran',
            name='description',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='img',
            field=models.ImageField(upload_to='media/{RestoranName}'),
        ),
    ]
