# Generated by Django 4.2.1 on 2023-05-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_restoran_restoranname_alter_restoran_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restorans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RestoranName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Restorans_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('img', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.restorans')),
            ],
        ),
        migrations.DeleteModel(
            name='Restoran',
        ),
    ]
