# Generated by Django 4.2.1 on 2023-05-28 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_restorans_restorans_menu_delete_restoran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorans_menu',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restorans', to='shop.restorans'),
        ),
    ]
