# Generated by Django 4.2.1 on 2023-05-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_restorans_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorans_menu',
            name='group',
            field=models.CharField(choices=[('KFC', 'KFC'), ('PapaJoe', 'PapaJoe'), ('McDonalds', 'McDonalds'), ('etc...', 'etc')], default='McDonalds', max_length=20),
        ),
        migrations.AlterField(
            model_name='restorans_menu',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
