# Generated by Django 4.2.1 on 2023-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_restorans_menu_group_alter_restorans_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorans_menu',
            name='group',
            field=models.CharField(choices=[('PapaJoe', 'PapaJoe'), ('etc', 'etc'), ('Kfc', 'Kfc'), ('McDonalds', 'McDonalds')], default='McDonalds', max_length=20),
        ),
    ]
