# Generated by Django 4.2.1 on 2023-05-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_restorans_menu_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorans_menu',
            name='group',
            field=models.CharField(choices=[('Kfc', 'Kfc'), ('etc', 'etc'), ('PapaJoe', 'PapaJoe'), ('McDonalds', 'McDonalds')], default='McDonalds', max_length=20),
        ),
    ]
