# Generated by Django 4.2.1 on 2023-05-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_restorans_menu_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='restorans_menu',
            name='group',
            field=models.CharField(choices=[('etc', 'etc'), ('Kfc', 'Kfc'), ('McDonalds', 'McDonalds'), ('PapaJoe', 'PapaJoe')], default='McDonalds', max_length=20),
        ),
    ]
