# Generated by Django 4.2.1 on 2023-05-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_restorans_menu_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='name',
            new_name='order_name',
        ),
        migrations.AlterField(
            model_name='restorans_menu',
            name='group',
            field=models.CharField(choices=[('McDonalds', 'McDonalds'), ('etc', 'etc'), ('PapaJoe', 'PapaJoe'), ('Kfc', 'Kfc')], default='McDonalds', max_length=20),
        ),
    ]
