# Generated by Django 4.2.1 on 2023-05-28 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_name_basket_order_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='order_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.restorans_menu'),
        ),
        migrations.AlterField(
            model_name='restorans_menu',
            name='group',
            field=models.CharField(choices=[('McDonalds', 'McDonalds'), ('Kfc', 'Kfc'), ('PapaJoe', 'PapaJoe'), ('etc', 'etc')], default='McDonalds', max_length=20),
        ),
    ]
