# Generated by Django 4.2.1 on 2023-05-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_basket_order_name_alter_restorans_menu_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='order_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restorans_menu',
            name='group',
            field=models.CharField(choices=[('McDonalds', 'McDonalds'), ('etc', 'etc'), ('Kfc', 'Kfc'), ('PapaJoe', 'PapaJoe')], default='McDonalds', max_length=20),
        ),
    ]
